from setuptools import setup

setup(
    name='cetd',
    version='1.0',
    packages=['src.cetd', 'venv.lib.python3.6.distutils', 'venv.lib.python3.6.encodings',
              'venv.lib.python3.6.importlib', 'venv.lib.python3.6.collections', 'venv.lib.python3.6.site-packages.bs4',
              'venv.lib.python3.6.site-packages.bs4.tests', 'venv.lib.python3.6.site-packages.bs4.builder',
              'venv.lib.python3.6.site-packages.pip', 'venv.lib.python3.6.site-packages.pip.req',
              'venv.lib.python3.6.site-packages.pip.vcs', 'venv.lib.python3.6.site-packages.pip.utils',
              'venv.lib.python3.6.site-packages.pip.compat', 'venv.lib.python3.6.site-packages.pip.models',
              'venv.lib.python3.6.site-packages.pip._vendor', 'venv.lib.python3.6.site-packages.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip.commands', 'venv.lib.python3.6.site-packages.pip.operations',
              'venv.lib.python3.6.site-packages.zmq', 'venv.lib.python3.6.site-packages.zmq.log',
              'venv.lib.python3.6.site-packages.zmq.ssh', 'venv.lib.python3.6.site-packages.zmq.auth',
              'venv.lib.python3.6.site-packages.zmq.auth.asyncio', 'venv.lib.python3.6.site-packages.zmq.green',
              'venv.lib.python3.6.site-packages.zmq.green.eventloop', 'venv.lib.python3.6.site-packages.zmq.sugar',
              'venv.lib.python3.6.site-packages.zmq.tests', 'venv.lib.python3.6.site-packages.zmq.tests.asyncio',
              'venv.lib.python3.6.site-packages.zmq.utils', 'venv.lib.python3.6.site-packages.zmq.asyncio',
              'venv.lib.python3.6.site-packages.zmq.backend', 'venv.lib.python3.6.site-packages.zmq.backend.cffi',
              'venv.lib.python3.6.site-packages.zmq.backend.cython', 'venv.lib.python3.6.site-packages.zmq.devices',
              'venv.lib.python3.6.site-packages.zmq.eventloop',
              'venv.lib.python3.6.site-packages.zmq.eventloop.minitornado',
              'venv.lib.python3.6.site-packages.zmq.eventloop.minitornado.platform',
              'venv.lib.python3.6.site-packages.wheel', 'venv.lib.python3.6.site-packages.wheel.tool',
              'venv.lib.python3.6.site-packages.wheel.signatures', 'venv.lib.python3.6.site-packages.bleach',
              'venv.lib.python3.6.site-packages.jinja2', 'venv.lib.python3.6.site-packages.appnope',
              'venv.lib.python3.6.site-packages.IPython', 'venv.lib.python3.6.site-packages.IPython.lib',
              'venv.lib.python3.6.site-packages.IPython.lib.tests', 'venv.lib.python3.6.site-packages.IPython.core',
              'venv.lib.python3.6.site-packages.IPython.core.tests',
              'venv.lib.python3.6.site-packages.IPython.core.magics', 'venv.lib.python3.6.site-packages.IPython.utils',
              'venv.lib.python3.6.site-packages.IPython.utils.tests', 'venv.lib.python3.6.site-packages.IPython.kernel',
              'venv.lib.python3.6.site-packages.IPython.testing',
              'venv.lib.python3.6.site-packages.IPython.testing.tests',
              'venv.lib.python3.6.site-packages.IPython.testing.plugin',
              'venv.lib.python3.6.site-packages.IPython.external',
              'venv.lib.python3.6.site-packages.IPython.external.decorators',
              'venv.lib.python3.6.site-packages.IPython.terminal',
              'venv.lib.python3.6.site-packages.IPython.terminal.tests',
              'venv.lib.python3.6.site-packages.IPython.terminal.pt_inputhooks',
              'venv.lib.python3.6.site-packages.IPython.sphinxext',
              'venv.lib.python3.6.site-packages.IPython.extensions',
              'venv.lib.python3.6.site-packages.IPython.extensions.tests', 'venv.lib.python3.6.site-packages.pexpect',
              'venv.lib.python3.6.site-packages.tornado', 'venv.lib.python3.6.site-packages.tornado.test',
              'venv.lib.python3.6.site-packages.tornado.platform', 'venv.lib.python3.6.site-packages.wcwidth',
              'venv.lib.python3.6.site-packages.wcwidth.tests', 'venv.lib.python3.6.site-packages.dateutil',
              'venv.lib.python3.6.site-packages.dateutil.tz', 'venv.lib.python3.6.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.6.site-packages.html5lib', 'venv.lib.python3.6.site-packages.html5lib._trie',
              'venv.lib.python3.6.site-packages.html5lib.filters',
              'venv.lib.python3.6.site-packages.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.html5lib.treebuilders', 'venv.lib.python3.6.site-packages.nbformat',
              'venv.lib.python3.6.site-packages.nbformat.v1', 'venv.lib.python3.6.site-packages.nbformat.v1.tests',
              'venv.lib.python3.6.site-packages.nbformat.v2', 'venv.lib.python3.6.site-packages.nbformat.v2.tests',
              'venv.lib.python3.6.site-packages.nbformat.v3', 'venv.lib.python3.6.site-packages.nbformat.v3.tests',
              'venv.lib.python3.6.site-packages.nbformat.v4', 'venv.lib.python3.6.site-packages.nbformat.v4.tests',
              'venv.lib.python3.6.site-packages.nbformat.tests', 'venv.lib.python3.6.site-packages.notebook',
              'venv.lib.python3.6.site-packages.notebook.auth', 'venv.lib.python3.6.site-packages.notebook.auth.tests',
              'venv.lib.python3.6.site-packages.notebook.base', 'venv.lib.python3.6.site-packages.notebook.edit',
              'venv.lib.python3.6.site-packages.notebook.tree', 'venv.lib.python3.6.site-packages.notebook.tree.tests',
              'venv.lib.python3.6.site-packages.notebook.view', 'venv.lib.python3.6.site-packages.notebook.files',
              'venv.lib.python3.6.site-packages.notebook.tests', 'venv.lib.python3.6.site-packages.notebook.bundler',
              'venv.lib.python3.6.site-packages.notebook.bundler.tests',
              'venv.lib.python3.6.site-packages.notebook.notebook',
              'venv.lib.python3.6.site-packages.notebook.services',
              'venv.lib.python3.6.site-packages.notebook.services.api',
              'venv.lib.python3.6.site-packages.notebook.services.api.tests',
              'venv.lib.python3.6.site-packages.notebook.services.config',
              'venv.lib.python3.6.site-packages.notebook.services.config.tests',
              'venv.lib.python3.6.site-packages.notebook.services.kernels',
              'venv.lib.python3.6.site-packages.notebook.services.kernels.tests',
              'venv.lib.python3.6.site-packages.notebook.services.contents',
              'venv.lib.python3.6.site-packages.notebook.services.contents.tests',
              'venv.lib.python3.6.site-packages.notebook.services.security',
              'venv.lib.python3.6.site-packages.notebook.services.sessions',
              'venv.lib.python3.6.site-packages.notebook.services.sessions.tests',
              'venv.lib.python3.6.site-packages.notebook.services.nbconvert',
              'venv.lib.python3.6.site-packages.notebook.services.nbconvert.tests',
              'venv.lib.python3.6.site-packages.notebook.services.kernelspecs',
              'venv.lib.python3.6.site-packages.notebook.services.kernelspecs.tests',
              'venv.lib.python3.6.site-packages.notebook.terminal',
              'venv.lib.python3.6.site-packages.notebook.nbconvert',
              'venv.lib.python3.6.site-packages.notebook.nbconvert.tests',
              'venv.lib.python3.6.site-packages.notebook.kernelspecs', 'venv.lib.python3.6.site-packages.pygments',
              'venv.lib.python3.6.site-packages.pygments.lexers', 'venv.lib.python3.6.site-packages.pygments.styles',
              'venv.lib.python3.6.site-packages.pygments.filters',
              'venv.lib.python3.6.site-packages.pygments.formatters', 'venv.lib.python3.6.site-packages.testpath',
              'venv.lib.python3.6.site-packages.ipykernel', 'venv.lib.python3.6.site-packages.ipykernel.gui',
              'venv.lib.python3.6.site-packages.ipykernel.comm', 'venv.lib.python3.6.site-packages.ipykernel.pylab',
              'venv.lib.python3.6.site-packages.ipykernel.tests',
              'venv.lib.python3.6.site-packages.ipykernel.inprocess',
              'venv.lib.python3.6.site-packages.ipykernel.inprocess.tests',
              'venv.lib.python3.6.site-packages.nbconvert', 'venv.lib.python3.6.site-packages.nbconvert.tests',
              'venv.lib.python3.6.site-packages.nbconvert.utils',
              'venv.lib.python3.6.site-packages.nbconvert.utils.tests',
              'venv.lib.python3.6.site-packages.nbconvert.filters',
              'venv.lib.python3.6.site-packages.nbconvert.filters.tests',
              'venv.lib.python3.6.site-packages.nbconvert.writers',
              'venv.lib.python3.6.site-packages.nbconvert.writers.tests',
              'venv.lib.python3.6.site-packages.nbconvert.exporters',
              'venv.lib.python3.6.site-packages.nbconvert.exporters.tests',
              'venv.lib.python3.6.site-packages.nbconvert.resources',
              'venv.lib.python3.6.site-packages.nbconvert.preprocessors',
              'venv.lib.python3.6.site-packages.nbconvert.preprocessors.tests',
              'venv.lib.python3.6.site-packages.nbconvert.postprocessors',
              'venv.lib.python3.6.site-packages.nbconvert.postprocessors.tests',
              'venv.lib.python3.6.site-packages.qtconsole', 'venv.lib.python3.6.site-packages.qtconsole.tests',
              'venv.lib.python3.6.site-packages.terminado', 'venv.lib.python3.6.site-packages.terminado.tests',
              'venv.lib.python3.6.site-packages.traitlets', 'venv.lib.python3.6.site-packages.traitlets.tests',
              'venv.lib.python3.6.site-packages.traitlets.utils',
              'venv.lib.python3.6.site-packages.traitlets.utils.tests',
              'venv.lib.python3.6.site-packages.traitlets.config',
              'venv.lib.python3.6.site-packages.traitlets.config.tests', 'venv.lib.python3.6.site-packages.ipywidgets',
              'venv.lib.python3.6.site-packages.ipywidgets.tests',
              'venv.lib.python3.6.site-packages.ipywidgets.widgets',
              'venv.lib.python3.6.site-packages.ipywidgets.widgets.tests',
              'venv.lib.python3.6.site-packages.jsonschema', 'venv.lib.python3.6.site-packages.jsonschema.tests',
              'venv.lib.python3.6.site-packages.markupsafe', 'venv.lib.python3.6.site-packages.ptyprocess',
              'venv.lib.python3.6.site-packages.setuptools', 'venv.lib.python3.6.site-packages.setuptools.extern',
              'venv.lib.python3.6.site-packages.setuptools.command', 'venv.lib.python3.6.site-packages.jupyter_core',
              'venv.lib.python3.6.site-packages.jupyter_core.tests',
              'venv.lib.python3.6.site-packages.jupyter_core.utils', 'venv.lib.python3.6.site-packages.webencodings',
              'venv.lib.python3.6.site-packages.pkg_resources', 'venv.lib.python3.6.site-packages.pkg_resources.extern',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python3.6.site-packages.jupyter_client',
              'venv.lib.python3.6.site-packages.jupyter_client.tests',
              'venv.lib.python3.6.site-packages.jupyter_client.ioloop',
              'venv.lib.python3.6.site-packages.jupyter_client.blocking',
              'venv.lib.python3.6.site-packages.prompt_toolkit',
              'venv.lib.python3.6.site-packages.prompt_toolkit.layout',
              'venv.lib.python3.6.site-packages.prompt_toolkit.styles',
              'venv.lib.python3.6.site-packages.prompt_toolkit.contrib',
              'venv.lib.python3.6.site-packages.prompt_toolkit.contrib.telnet',
              'venv.lib.python3.6.site-packages.prompt_toolkit.contrib.completers',
              'venv.lib.python3.6.site-packages.prompt_toolkit.contrib.validators',
              'venv.lib.python3.6.site-packages.prompt_toolkit.contrib.regular_languages',
              'venv.lib.python3.6.site-packages.prompt_toolkit.filters',
              'venv.lib.python3.6.site-packages.prompt_toolkit.terminal',
              'venv.lib.python3.6.site-packages.prompt_toolkit.clipboard',
              'venv.lib.python3.6.site-packages.prompt_toolkit.eventloop',
              'venv.lib.python3.6.site-packages.prompt_toolkit.key_binding',
              'venv.lib.python3.6.site-packages.prompt_toolkit.key_binding.bindings',
              'venv.lib.python3.6.site-packages.jupyter_console',
              'venv.lib.python3.6.site-packages.jupyter_console.tests',
              'venv.lib.python3.6.site-packages.ipython_genutils',
              'venv.lib.python3.6.site-packages.ipython_genutils.tests',
              'venv.lib.python3.6.site-packages.ipython_genutils.testing',
              'venv.lib.python3.6.site-packages.widgetsnbextension'],
    url='http://www.github.com/benprofessionaledition',
    license='MIT',
    author='ben levine',
    author_email='ben.h.levine@gmail.com',
    description='Algorithm for extracting relevant bits of raw webpage HTML'
)
